#専用サーバー
#Download >>> https://github.com/psac-serve/ban-server/ <<<
server:
  #アドレス:ポート番号
  addr: "localhost:810"
  #認証用トークン
  token: ""
  #Msgpackを使用するかどうか
  msgpack: true

messageFile: message-ja.yml