#専用サーバー
#Download >>> https://github.com/psac-serve/ban-server/ <<<
server:
  #アドレス:ポート番号
  addr: "localhost:810"
  #認証用トークン
  token: ""

#BungeeCord(Waterfall)の有無
bungeecord: false

#きっく！
kick:
  #キックまでのメッセージが流れてからのラグ(秒
  lag: 1